### PR TITLE
Testing autogluon.timeseries build on osx and arm64

### PR DESCRIPTION
**Pull request by giswqs**
The `noarch` build is faster and recommended by conda-forge when possible, but it is only built and tested on Linux. This PR tries to move away from `noarch` build so that we can test the import on different platforms (e.g., osx, arm64, win). 

https://github.com/autogluon/autogluon/issues/2929

@gradientsky @Innixma 

Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by giswqs** [comment]
@conda-forge-admin, please rerender

**Review by Innixma — APPROVED** [review]
LGTM!

**Comment by giswqs** [comment]
@conda-forge-admin, please rerender

**Comment by giswqs** [comment]
@conda-forge-admin, please rerender

**Comment by giswqs** [comment]
@conda-forge-admin, please rerender

**Comment by giswqs** [comment]
@conda-forge-admin, please rerender

**Comment by giswqs** [comment]
`sktime` now supports Python 3.10. Rebuilding the recipe to add support for Python 3.10.
https://github.com/conda-forge/sktime-feedstock/pull/64
https://github.com/conda-forge/sktime-feedstock/pull/65

**Pull request closed without merging**
